dataset:
  path: "/home/linuxu/ben/Final Project/"
  low_resolution_dir: "/home/linuxu/ben/Final Project/LR"
  patches_dir: "/home/linuxu/ben/Final Project/LR-Patches"
  inference_result_dir: "/home/linuxu/ben/Final Project/SR-Patches"
  reconstructed_images_dir: "/home/linuxu/ben/Final Project/SR"
  original_image_height: 64
  original_image_width: 64

processing:
  model_path: "src/processing/fsrcnn_x2-T91-f791f07f.pth.tar"
  patch_size: 16
  upscale_factor: 2

paths:
  original_image: grayscale_003.jpg
  output_image: grayscale_003.jpg
